import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { listEntries } from "@/helpers/api";
import { Entry, EntryType } from "@/helpers/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const types = await listEntries<Entry>("collections", true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between bg-[#111]">
          <div className="grid grid-cols-[1fr_5fr] w-full h-full min-h-screen max-w-[1000px]">
            <div className="flex flex-col p-24 border-r-[1px] border-[#333] gap-4 h-full">
              {types &&
                Object.values(types).map((type: Entry) => {
                  return (
                    <Link
                      key={`${type.id}`}
                      href={`/dashboard/collection/${type.id}`}
                    >
                      <div>{type.name}</div>
                    </Link>
                  );
                })}
              <hr />
              <Link href="/dashboard/types">types</Link>
              <Link href="/dashboard/collections">collections</Link>
            </div>
            <div className="flex flex-col h-full p-24">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
